# Generated by Django 3.1 on 2021-03-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='picture',
        ),
    ]
