# Generated by Django 3.1 on 2021-04-04 18:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
