# Generated by Django 3.1 on 2021-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20210404_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tweet',
            new_name='TweetDB',
        ),
    ]
