# Generated by Django 3.2.7 on 2021-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_auto_20210407_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdb',
            name='like_count',
        ),
        migrations.AddField(
            model_name='tweetdb',
            name='likes',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='like'),
        ),
    ]
